# Generated by Django 4.0.4 on 2023-04-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
