# Generated by Django 4.0.4 on 2023-04-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookest', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='_id',
            field=models.CharField(default='dummy id', max_length=200),
            preserve_default=False,
        ),
    ]
