# Generated by Django 4.0.4 on 2023-04-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookest', '0003_review__id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhasbeenread',
            options={'verbose_name_plural': 'Users HasBeenRead Shelfs Ordered'},
        ),
        migrations.AlterModelOptions(
            name='orderwillberead',
            options={'verbose_name_plural': 'Users WillbeRead Shelfs Ordered'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Notes on books'},
        ),
    ]
